In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import IsolationForest

data = {
    "date": [
        "2026-09-01",
        "2026-09-02",
        "2026-09-03",
        "2026-09-04",
        "2026-09-05",
        "2026-09-06",
        "2026-09-07",
        "2026-09-08",
        "2026-09-09",
        "2026-09-10"
    ],

    "name": [
        "Canteen",
        "Bus",
        "Swiggy",
        "Canteen",
        "Uber",
        "Amazon",
        "Canteen",
        "Swiggy",
        "Bus",
        "Restaurant"
    ],

    "amount": [
        80,
        40,
        250,
        100,
        180,
        700,
        90,
        220,
        50,
        2500
    ],

    "category": [
        "Food",
        "Transport",
        "Food",
        "Food",
        "Transport",
        "Shopping",
        "Food",
        "Food",
        "Transport",
        "Food"
    ],

    "account": [
        "Savings",
        "Savings",
        "Savings",
        "Savings",
        "Savings",
        "Savings",
        "Savings",
        "Savings",
        "Savings",
        "Savings"
    ],

    "type": [
        "Expense",
        "Expense",
        "Expense",
        "Expense",
        "Expense",
        "Expense",
        "Expense",
        "Expense",
        "Expense",
        "Expense"
    ]
}

df = pd.DataFrame(data)

df

         date        name  amount   category  account     type
0  2026-09-01     Canteen      80       Food  Savings  Expense
1  2026-09-02         Bus      40  Transport  Savings  Expense
2  2026-09-03      Swiggy     250       Food  Savings  Expense
3  2026-09-04     Canteen     100       Food  Savings  Expense
4  2026-09-05        Uber     180  Transport  Savings  Expense
5  2026-09-06      Amazon     700   Shopping  Savings  Expense
6  2026-09-07     Canteen      90       Food  Savings  Expense
7  2026-09-08      Swiggy     220       Food  Savings  Expense
8  2026-09-09         Bus      50  Transport  Savings  Expense
9  2026-09-10  Restaurant    2500       Food  Savings  Expense

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      10 non-null     object
 1   name      10 non-null     object
 2   amount    10 non-null     int64
 3   category  10 non-null     object
 4   account   10 non-null     object
 5   type      10 non-null     object
dtypes: int64(1), object(5)
memory usage: 612.0+ bytes

In [ ]:
df.describe()

            amount
count    10.000000
mean    421.000000
std     755.681444
min      40.000000
25%      82.500000
50%     140.000000
75%     242.500000
max    2500.000000

In [ ]:
df["category"].value_counts()

category
Food         6
Transport    3
Shopping     1
Name: count, dtype: int64

In [ ]:
X = df[["amount"]]
X

   amount
0      80
1      40
2     250
3     100
4     180
5     700
6      90
7     220
8      50
9    2500

In [ ]:
model = IsolationForest(contamination=0.1, random_state=42)
model.fit(X)

IsolationForest(contamination=0.1, random_state=42)

In [ ]:
df["prediction"] = model.predict(X)

df

         date        name  amount   category  account     type  prediction
0  2026-09-01     Canteen      80       Food  Savings  Expense           1
1  2026-09-02         Bus      40  Transport  Savings  Expense           1
2  2026-09-03      Swiggy     250       Food  Savings  Expense           1
3  2026-09-04     Canteen     100       Food  Savings  Expense           1
4  2026-09-05        Uber     180  Transport  Savings  Expense           1
5  2026-09-06      Amazon     700   Shopping  Savings  Expense           1
6  2026-09-07     Canteen      90       Food  Savings  Expense           1
7  2026-09-08      Swiggy     220       Food  Savings  Expense           1
8  2026-09-09         Bus      50  Transport  Savings  Expense           1
9  2026-09-10  Restaurant    2500       Food  Savings  Expense          -1

In [ ]:
anomalies = df[df["prediction"] == -1]

anomalies

         date        name  amount category  account     type  prediction
9  2026-09-10  Restaurant    2500     Food  Savings  Expense          -1

In [ ]:
df[df["prediction"] == -1]

         date        name  amount category  account     type  prediction
9  2026-09-10  Restaurant    2500     Food  Savings  Expense          -1

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 1000

categories = [
    "Food",
    "Transport",
    "Shopping",
    "Entertainment",
    "Education",
    "Healthcare",
    "Bills"
]

category_names = {
    "Food": ["Canteen", "Swiggy", "Zomato", "Restaurant"],
    "Transport": ["Bus", "Uber", "Ola", "Metro"],
    "Shopping": ["Amazon", "Myntra", "Local Store"],
    "Entertainment": ["Netflix", "PVR", "Gaming"],
    "Education": ["Udemy", "Books", "College"],
    "Healthcare": ["Pharmacy", "Clinic"],
    "Bills": ["Electricity", "Internet", "Mobile"]
}

category_amounts = {
    "Food": (80, 500),
    "Transport": (30, 300),
    "Shopping": (200, 2000),
    "Entertainment": (100, 1000),
    "Education": (100, 1500),
    "Healthcare": (100, 1200),
    "Bills": (200, 1500)
}

dates = pd.date_range(
    start="2026-07-01",
    end="2026-09-30",
    periods=n
)

rows = []

for date in dates:
    category = np.random.choice(categories)

    name = np.random.choice(category_names[category])

    low, high = category_amounts[category]
    amount = np.random.randint(low, high + 1)

    account = np.random.choice(
        ["Savings", "Cash", "Credit"],
        p=[0.6, 0.25, 0.15]
    )

    rows.append([
        date,
        name,
        amount,
        category,
        account,
        "Expense",
        ""
    ])

df = pd.DataFrame(
    rows,
    columns=[
        "date",
        "name",
        "amount",
        "category",
        "account",
        "type",
        "note"
    ]
)

df.head()

,date,name,amount,category,account,type,note
0,2026-07-01 00:00:00.000000000,Electricity,1494,Bills,Cash,Expense,
1,2026-07-01 02:11:10.270270270,Udemy,221,Education,Savings,Expense,
2,2026-07-01 04:22:20.540540540,Local Store,287,Shopping,Savings,Expense,
3,2026-07-01 06:33:30.810810810,Myntra,1532,Shopping,Credit,Expense,
4,2026-07-01 08:44:41.081081081,PVR,905,Entertainment,Savings,Expense,

In [ ]:
df.describe()

                                date       amount
count                           1000  1000.000000
mean   2026-08-15 11:59:59.999999744   635.849000
min              2026-07-01 00:00:00    30.000000
25%              2026-07-23 18:00:00   258.000000
50%              2026-08-15 12:00:00   520.500000
75%              2026-09-07 06:00:00   933.500000
max              2026-09-30 00:00:00  1999.000000
std                              NaN   446.200268

In [ ]:
df.shape

(1000, 7)

In [ ]:
df["category"].value_counts()

category
Shopping         153
Education        152
Healthcare       150
Transport        148
Food             139
Entertainment    135
Bills            123
Name: count, dtype: int64

In [ ]:
df["amount"].describe()

count    1000.000000
mean      635.849000
std       446.200268
min        30.000000
25%       258.000000
50%       520.500000
75%       933.500000
max      1999.000000
Name: amount, dtype: float64

In [ ]:
X = df[["amount"]]

In [ ]:
print(X.head())

   amount
0    1494
1     221
2     287
3    1532
4     905

In [ ]:
from sklearn.ensemble import IsolationForest
model = IsolationForest(contamination=0.05, random_state=42)
model.fit(X)

IsolationForest(contamination=0.05, random_state=42)

In [ ]:
df["prediction"] = model.predict(X)

In [ ]:
df["prediction"].value_counts()

prediction
 1    950
-1     50
Name: count, dtype: int64

In [ ]:
anomalies = df[df["prediction"] == -1]

anomalies[["date", "name", "amount", "category", "account"]].sort_values(
    by="amount",
    ascending=False
).head(20)

                             date         name  amount  category  account
77  2026-07-08 00:20:10.810810810       Myntra    1999  Shopping     Cash
385 2026-08-05 01:40:54.054054054       Myntra    1976  Shopping  Savings
771 2026-09-09 05:32:58.378378379       Amazon    1962  Shopping  Savings
899 2026-09-20 21:22:52.972972973       Amazon    1939  Shopping  Savings
679 2026-08-31 20:25:13.513513514  Local Store    1933  Shopping   Credit
98  2026-07-09 22:14:46.486486486       Amazon    1921  Shopping  Savings
713 2026-09-03 22:45:02.702702703       Amazon    1902  Shopping  Savings
123 2026-07-12 04:54:03.243243243       Myntra    1898  Shopping     Cash
905 2026-09-21 10:29:54.594594595       Amazon    1897  Shopping  Savings
963 2026-09-26 17:17:50.270270270  Local Store    1891  Shopping     Cash
113 2026-07-11 07:02:20.540540540       Myntra    1879  Shopping  Savings
914 2026-09-22 06:10:27.027027027  Local Store    1875  Shopping   Credit
420 2026-08-08 06:11:53.513513513       Amazon    1869  Shopping  Savings
651 2026-08-29 07:12:25.945945946  Local Store    1853  Shopping  Savings
756 2026-09-07 20:45:24.324324325       Amazon    1852  Shopping  Savings
966 2026-09-26 23:51:21.081081081       Amazon    1824  Shopping   Credit
551 2026-08-20 04:35:18.918918919  Local Store    1820  Shopping     Cash
776 2026-09-09 16:28:49.729729730  Local Store    1799  Shopping     Cash
380 2026-08-04 14:45:02.702702703       Amazon    1798  Shopping  Savings
870 2026-09-18 05:58:55.135135135  Local Store    1789  Shopping  Savings

In [ ]:
category_stats = df.groupby("category")["amount"].agg(
    category_mean="mean",
    category_std="std"
)

category_stats

               category_mean  category_std
category
Bills             905.520325    381.140058
Education         773.565789    403.177654
Entertainment     564.800000    261.805864
Food              303.107914    115.328308
Healthcare        654.306667    322.579868
Shopping         1078.738562    507.938050
Transport         171.047297     80.456972

In [ ]:
df = df.merge(
    category_stats,
    left_on="category",
    right_index=True
)

In [ ]:
df[["amount", "category", "category_mean", "category_std"]].head()

   amount       category  category_mean  category_std
0    1494          Bills     905.520325    381.140058
1     221      Education     773.565789    403.177654
2     287       Shopping    1078.738562    507.938050
3    1532       Shopping    1078.738562    507.938050
4     905  Entertainment     564.800000    261.805864

In [ ]:
df["category_zscore"] = (
    df["amount"] - df["category_mean"]
) / df["category_std"]

In [ ]:
df[
    ["amount", "category", "category_mean", "category_zscore"]
].sort_values(
    "category_zscore",
    ascending=False
).head(20)

     amount       category  category_mean  category_zscore
77     1999       Shopping    1078.738562         1.811759
995    1491      Education     773.565789         1.779449
385    1976       Shopping    1078.738562         1.766478
708    1477      Education     773.565789         1.744725
771    1962       Shopping    1078.738562         1.738916
534    1468      Education     773.565789         1.722403
154    1465      Education     773.565789         1.714962
899    1939       Shopping    1078.738562         1.693635
679    1933       Shopping    1078.738562         1.681822
210    1196     Healthcare     654.306667         1.679253
779    1447      Education     773.565789         1.670316
114    1192     Healthcare     654.306667         1.666853
842    1192     Healthcare     654.306667         1.666853
446     495           Food     303.107914         1.663877
98     1921       Shopping    1078.738562         1.658197
883    1189     Healthcare     654.306667         1.657553
919     997  Entertainment     564.800000         1.650842
672    1437      Education     773.565789         1.645513
592    1183     Healthcare     654.306667         1.638953
713    1902       Shopping    1078.738562         1.620791

In [ ]:
X = df[["category_zscore"]]

In [ ]:
model = IsolationForest(
    contamination=0.05,
    random_state=42
)

model.fit(X)

IsolationForest(contamination=0.05, random_state=42)

In [ ]:
df["prediction_v2"] = model.predict(X)

In [ ]:
anomalies_v2 = df[df["prediction_v2"] == -1]

anomalies_v2[
    [
        "date",
        "name",
        "amount",
        "category",
        "category_mean",
        "category_zscore"
    ]
].sort_values(
    "category_zscore",
    ascending=False
).head(20)

,date,name,amount,category,category_mean,category_zscore
77,2026-07-08 00:20:10.810810810,Myntra,1999,Shopping,1078.738562,1.811759
995,2026-09-29 15:15:18.918918919,Udemy,1491,Education,773.565789,1.779449
385,2026-08-05 01:40:54.054054054,Myntra,1976,Shopping,1078.738562,1.766478
708,2026-09-03 11:49:11.351351352,Udemy,1477,Education,773.565789,1.744725
771,2026-09-09 05:32:58.378378379,Amazon,1962,Shopping,1078.738562,1.738916
534,2026-08-18 15:25:24.324324324,Books,1468,Education,773.565789,1.722403
154,2026-07-15 00:40:21.621621621,Udemy,1465,Education,773.565789,1.714962
899,2026-09-20 21:22:52.972972973,Amazon,1939,Shopping,1078.738562,1.693635
679,2026-08-31 20:25:13.513513514,Local Store,1933,Shopping,1078.738562,1.681822
210,2026-07-20 03:05:56.756756756,Clinic,1196,Healthcare,654.306667,1.679253
779,2026-09-09 23:02:20.540540541,Udemy,1447,Education,773.565789,1.670316
114,2026-07-11 09:13:30.810810810,Pharmacy,1192,Healthcare,654.306667,1.666853
842,2026-09-15 16:46:07.567567568,Clinic,1192,Healthcare,654.306667,1.666853
446,2026-08-10 15:02:20.540540540,Swiggy,495,Food,303.107914,1.663877
98,2026-07-09 22:14:46.486486486,Amazon,1921,Shopping,1078.738562,1.658197
883,2026-09-19 10:24:08.648648649,Clinic,1189,Healthcare,654.306667,1.657553
919,2026-09-22 17:06:18.378378379,Gaming,997,Entertainment,564.800000,1.650842
672,2026-08-31 05:07:01.621621622,Books,1437,Education,773.565789,1.645513
592,2026-08-23 22:13:20.000000000,Clinic,1183,Healthcare,654.306667,1.638953
713,2026-09-03 22:45:02.702702703,Amazon,1902,Shopping,1078.738562,1.620791

In [ ]:
normal_df = df.copy()

In [ ]:
anomaly_df = normal_df.sample(20, random_state=42).copy()

anomaly_df["original_amount"] = anomaly_df["amount"]

anomaly_df["amount"] = anomaly_df["amount"] * 5

anomaly_df["ground_truth"] = 1

In [ ]:
normal_test = normal_df.sample(100, random_state=10).copy()
normal_test["ground_truth"] = 0

In [ ]:
test_df = pd.concat(
    [normal_test, anomaly_df],
    ignore_index=True
)

In [ ]:
base_df = pd.DataFrame(data)

In [ ]:
base_df.shape

(10, 6)

In [ ]:
df.shape

(1000, 12)

In [ ]:
base_df = df[
    ["date", "name", "amount", "category", "account", "type", "note"]
].copy()

In [ ]:
print(base_df.shape)

(1000, 7)

In [ ]:
normal_df = base_df.copy()

In [ ]:
normal_df.head()

,date,name,amount,category,account,type,note
0,2026-07-01 00:00:00.000000000,Electricity,1494,Bills,Cash,Expense,
1,2026-07-01 02:11:10.270270270,Udemy,221,Education,Savings,Expense,
2,2026-07-01 04:22:20.540540540,Local Store,287,Shopping,Savings,Expense,
3,2026-07-01 06:33:30.810810810,Myntra,1532,Shopping,Credit,Expense,
4,2026-07-01 08:44:41.081081081,PVR,905,Entertainment,Savings,Expense,

In [ ]:
print(base_df.shape)
print(base_df.columns.tolist())

(1000, 7)
['date', 'name', 'amount', 'category', 'account', 'type', 'note']

In [ ]:
# Clean normal dataset
normal_df = base_df.copy()

# Take 100 normal transactions for testing
normal_test = normal_df.sample(100, random_state=10).copy()
normal_test["ground_truth"] = 0

# Create 20 artificial anomalies
anomaly_test = normal_df.sample(20, random_state=42).copy()

anomaly_test["original_amount"] = anomaly_test["amount"]

# Make these transactions unusually expensive
anomaly_test["amount"] = anomaly_test["amount"] * 5

anomaly_test["ground_truth"] = 1

# Combine normal + abnormal transactions
test_df = pd.concat(
    [normal_test, anomaly_test],
    ignore_index=True
)

print(test_df.shape)

(120, 9)

In [ ]:
test_df[[
    "name",
    "amount",
    "category",
    "ground_truth"
]].head(10)

       name  amount    category  ground_truth
0    Clinic     208  Healthcare             0
1    Swiggy     490        Food             0
2  Internet    1056       Bills             0
3     Udemy     839   Education             0
4       Ola     254   Transport             0
5     Udemy     558   Education             0
6     Udemy     615   Education             0
7  Internet    1042       Bills             0
8  Internet     587       Bills             0
9       Ola     125   Transport             0

In [ ]:
test_df.shape

(120, 9)

In [ ]:
from sklearn.ensemble import IsolationForest

X_train = normal_df[["amount"]]

model = IsolationForest(
    contamination=0.05,
    random_state=42
)

model.fit(X_train)

IsolationForest(contamination=0.05, random_state=42)

In [ ]:
X_test = test_df[["amount"]]

test_df["prediction"] = model.predict(X_test)

In [ ]:
test_df["predicted_anomaly"] = test_df["prediction"].map({
    1: 0,
    -1: 1
})

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

y_true = test_df["ground_truth"]
y_pred = test_df["predicted_anomaly"]

print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print("\nClassification Report:")
print(classification_report(
    y_true,
    y_pred,
    target_names=["Normal", "Anomaly"]
))

Confusion Matrix:
[[96  4]
 [ 4 16]]

Classification Report:
              precision    recall  f1-score   support

      Normal       0.96      0.96      0.96       100
     Anomaly       0.80      0.80      0.80        20

    accuracy                           0.93       120
   macro avg       0.88      0.88      0.88       120
weighted avg       0.93      0.93      0.93       120

In [ ]:
test_df[
    ["name", "amount", "category", "ground_truth", "predicted_anomaly"]
].sort_values("amount", ascending=False).head(20)

            name  amount       category  ground_truth  predicted_anomaly
115       Amazon    9695       Shopping             1                  1
107       Myntra    8020       Shopping             1                  1
109       Mobile    7065          Bills             1                  1
101        Books    6915      Education             1                  1
117       Clinic    5945     Healthcare             1                  1
103       Clinic    5715     Healthcare             1                  1
100     Pharmacy    5630     Healthcare             1                  1
119          PVR    4765  Entertainment             1                  1
108          PVR    3970  Entertainment             1                  1
113  Local Store    3960       Shopping             1                  1
102      Netflix    3825  Entertainment             1                  1
105       Clinic    3795     Healthcare             1                  1
112     Internet    3610          Bills             1                  1
106       Mobile    3490          Bills             1                  1
104     Pharmacy    3425     Healthcare             1                  1
116     Pharmacy    2595     Healthcare             1                  1
91        Amazon    1696       Shopping             0                  1
30        Amazon    1589       Shopping             0                  1
66   Local Store    1549       Shopping             0                  1
12   Local Store    1529       Shopping             0                  0

In [ ]:
category_stats = normal_df.groupby("category")["amount"].agg(
    category_mean="mean",
    category_std="std"
)

category_stats

               category_mean  category_std
category
Bills             905.520325    381.140058
Education         773.565789    403.177654
Entertainment     564.800000    261.805864
Food              303.107914    115.328308
Healthcare        654.306667    322.579868
Shopping         1078.738562    507.938050
Transport         171.047297     80.456972

In [ ]:
train_df = normal_df.merge(
    category_stats,
    on="category",
    how="left"
)

test_v2 = test_df.merge(
    category_stats,
    on="category",
    how="left"
)

In [ ]:
train_df["category_zscore"] = (
    train_df["amount"] - train_df["category_mean"]
) / train_df["category_std"]

In [ ]:
test_v2["category_zscore"] = (
    test_v2["amount"] - test_v2["category_mean"]
) / test_v2["category_std"]

In [ ]:
test_v2[
    [
        "name",
        "amount",
        "category",
        "category_mean",
        "category_zscore",
        "ground_truth"
    ]
].sort_values(
    "category_zscore",
    ascending=False
).head(20)

,name,amount,category,category_mean,category_zscore,ground_truth
115,Amazon,9695,Shopping,1078.738562,16.963213,1
117,Clinic,5945,Healthcare,654.306667,16.401189,1
109,Mobile,7065,Bills,905.520325,16.160673,1
119,PVR,4765,Entertainment,564.800000,16.043185,1
103,Clinic,5715,Healthcare,654.306667,15.688187,1
100,Pharmacy,5630,Healthcare,654.306667,15.424687,1
101,Books,6915,Education,773.565789,15.232576,1
114,Ola,1365,Transport,171.047297,14.839643,1
107,Myntra,8020,Shopping,1078.738562,13.665567,1
108,PVR,3970,Entertainment,564.800000,13.006584,1
102,Netflix,3825,Entertainment,564.800000,12.452739,1
105,Clinic,3795,Healthcare,654.306667,9.736173,1
104,Pharmacy,3425,Healthcare,654.306667,8.589170,1
112,Internet,3610,Bills,905.520325,7.095763,1
106,Mobile,3490,Bills,905.520325,6.780919,1
116,Pharmacy,2595,Healthcare,654.306667,6.016164,1
113,Local Store,3960,Shopping,1078.738562,5.672466,1
118,Clinic,1205,Healthcare,654.306667,1.707153,1
47,Clinic,1189,Healthcare,654.306667,1.657553,0
1,Swiggy,490,Food,303.107914,1.620522,0

In [ ]:
amount

1387

In [ ]:
X_train_v2 = train_df[
    ["amount", "category_zscore"]
]

X_test_v2 = test_v2[
    ["amount", "category_zscore"]
]

In [ ]:
model_v2 = IsolationForest(
    contamination=0.05,
    random_state=42
)

model_v2.fit(X_train_v2)

IsolationForest(contamination=0.05, random_state=42)

In [ ]:
test_v2["prediction"] = model_v2.predict(X_test_v2)

test_v2["predicted_anomaly"] = test_v2["prediction"].map({
    1: 0,
    -1: 1
})

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(
    confusion_matrix(
        test_v2["ground_truth"],
        test_v2["predicted_anomaly"]
    )
)

print("\nClassification Report:")
print(
    classification_report(
        test_v2["ground_truth"],
        test_v2["predicted_anomaly"],
        target_names=["Normal", "Anomaly"]
    )
)

Confusion Matrix:
[[97  3]
 [ 2 18]]

Classification Report:
              precision    recall  f1-score   support

      Normal       0.98      0.97      0.97       100
     Anomaly       0.86      0.90      0.88        20

    accuracy                           0.96       120
   macro avg       0.92      0.94      0.93       120
weighted avg       0.96      0.96      0.96       120

In [ ]:
import joblib

joblib.dump(model_v2, "anomaly_model.pkl")

['anomaly_model.pkl']

In [ ]:
joblib.dump(category_stats, "category_stats.pkl")

['category_stats.pkl']

In [ ]:
def detect_anomaly(amount, category):
    stats = category_stats.loc[category]

    category_zscore = (
        amount - stats["category_mean"]
    ) / stats["category_std"]

    features = [[amount, category_zscore]]

    prediction = model_v2.predict(features)[0]

    if prediction == -1:
        return "Anomaly"
    else:
        return "Normal"

In [ ]:
print(detect_anomaly(2500, "Food"))

Anomaly

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [ ]:
print(detect_anomaly(300, "Food"))

Normal

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [ ]:
def detect_anomaly(amount, category):
    stats = category_stats.loc[category]

    category_zscore = (
        amount - stats["category_mean"]
    ) / stats["category_std"]

    features = pd.DataFrame(
        [[amount, category_zscore]],
        columns=["amount", "category_zscore"]
    )

    prediction = model_v2.predict(features)[0]

    if prediction == -1:
        return "Anomaly"
    else:
        return "Normal"

In [ ]:
print(detect_anomaly(2500, "Food"))

Anomaly

In [ ]:
print(detect_anomaly(300, "Food"))

Normal

In [ ]:
test_amounts = [100, 250, 500, 1000, 1500, 2500, 5000]

for amount in test_amounts:
    print(amount, "Food →", detect_anomaly(amount, "Food"))

100 Food → Normal
250 Food → Normal
500 Food → Anomaly
1000 Food → Anomaly
1500 Food → Anomaly
2500 Food → Anomaly
5000 Food → Anomaly

In [ ]:
import os

print(os.listdir())

['.config', 'anomaly_model.pkl', 'category_stats.pkl', 'sample_data']

In [ ]:
def analyze_expense(amount, category):
    stats = category_stats.loc[category]

    category_zscore = (
        amount - stats["category_mean"]
    ) / stats["category_std"]

    features = pd.DataFrame(
        [[amount, category_zscore]],
        columns=["amount", "category_zscore"]
    )

    prediction = model_v2.predict(features)[0]
    score = model_v2.decision_function(features)[0]

    if prediction == -1:
        status = "Anomaly"
    else:
        status = "Normal"

    return {
        "amount": amount,
        "category": category,
        "status": status,
        "anomaly_score": score,
        "category_average": stats["category_mean"],
        "category_zscore": category_zscore
    }

In [ ]:
result = analyze_expense(1500, "Food")
result

{'amount': 1500,
 'category': 'Food',
 'status': 'Anomaly',
 'anomaly_score': np.float64(-0.042354079970890024),
 'category_average': np.float64(303.10791366906477),
 'category_zscore': np.float64(10.37812921682013)}

In [ ]:
def explain_expense(amount, category):
    result = analyze_expense(amount, category)

    if result["status"] == "Anomaly":
        print(
            f"⚠️ Potentially unusual expense: ₹{amount} "
            f"spent on {category}."
        )
        print(
            f"Your average {category} expense is "
            f"₹{result['category_average']:.0f}."
        )
        print(
            f"This transaction is "
            f"{result['category_zscore']:.1f} standard deviations "
            f"above your category average."
        )
    else:
        print(
            f"✅ This ₹{amount} {category} expense "
            f"looks normal for your spending pattern."
        )

In [ ]:
explain_expense(1500, "Food")

⚠️ Potentially unusual expense: ₹1500 spent on Food.
Your average Food expense is ₹303.
This transaction is 10.4 standard deviations above your category average.

In [ ]:
explain_expense(200, "Food")

✅ This ₹200 Food expense looks normal for your spending pattern.

In [5]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 1000

categories = [
    "Food",
    "Transport",
    "Shopping",
    "Entertainment",
    "Education",
    "Healthcare",
    "Bills"
]

category_names = {
    "Food": ["Canteen", "Swiggy", "Zomato", "Restaurant"],
    "Transport": ["Bus", "Uber", "Ola", "Metro"],
    "Shopping": ["Amazon", "Myntra", "Local Store"],
    "Entertainment": ["Netflix", "PVR", "Gaming"],
    "Education": ["Udemy", "Books", "College"],
    "Healthcare": ["Pharmacy", "Clinic"],
    "Bills": ["Electricity", "Internet", "Mobile"]
}

category_amounts = {
    "Food": (80, 500),
    "Transport": (30, 300),
    "Shopping": (200, 2000),
    "Entertainment": (100, 1000),
    "Education": (100, 1500),
    "Healthcare": (100, 1200),
    "Bills": (200, 1500)
}

dates = pd.date_range(
    start="2026-07-01",
    end="2026-09-30",
    periods=n
)

rows = []

for date in dates:
    category = np.random.choice(categories)
    name = np.random.choice(category_names[category])

    low, high = category_amounts[category]
    amount = np.random.randint(low, high + 1)

    account = np.random.choice(
        ["Savings", "Cash", "Credit"],
        p=[0.6, 0.25, 0.15]
    )

    rows.append([
        date,
        name,
        amount,
        category,
        account,
        "Expense",
        ""
    ])

df = pd.DataFrame(
    rows,
    columns=[
        "date",
        "name",
        "amount",
        "category",
        "account",
        "type",
        "note"
    ]
)

print(df.shape)

(1000, 7)

In [6]:
from sklearn.ensemble import IsolationForest

base_df = df.copy()
normal_df = base_df.copy()

category_stats = normal_df.groupby("category")["amount"].agg(
    category_mean="mean",
    category_std="std"
)

train_df = normal_df.merge(
    category_stats,
    on="category",
    how="left"
)

train_df["category_zscore"] = (
    train_df["amount"] - train_df["category_mean"]
) / train_df["category_std"]

X_train = train_df[
    ["amount", "category_zscore"]
]

model_v2 = IsolationForest(
    contamination=0.05,
    random_state=42
)

model_v2.fit(X_train)

print("Model trained successfully!")

Model trained successfully!

In [7]:
def analyze_expense(amount, category):

    stats = category_stats.loc[category]

    category_zscore = (
        amount - stats["category_mean"]
    ) / stats["category_std"]

    features = pd.DataFrame(
        [[amount, category_zscore]],
        columns=["amount", "category_zscore"]
    )

    prediction = model_v2.predict(features)[0]

    return "Anomaly" if prediction == -1 else "Normal"


print("₹200 Food:", analyze_expense(200, "Food"))
print("₹1500 Food:", analyze_expense(1500, "Food"))

₹200 Food: Normal
₹1500 Food: Anomaly

In [8]:
import joblib

joblib.dump(model_v2, "/content/anomaly_model.pkl")
joblib.dump(category_stats, "/content/category_stats.pkl")

print("Files saved!")

Files saved!

In [9]:
import os

print(os.listdir("/content"))

['.config', 'anomaly_model.pkl', 'category_stats.pkl', 'sample_data']